cohabio/cohabio/urls.py
from django.contrib import admin
from django.urls import include, path


handler400 = 'mapper.views.bad_request'
handler403 = 'mapper.views.permission_denied'
handler404 = 'mapper.views.page_not_found'
handler500 = 'mapper.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mapper.urls', namespace='mapper'))
]

cohabio/mapper/urls.py
from django.urls import path
from . import views

app_name = 'mapper'
urlpatterns = [
    path('', views.index, name='index'),
    path('index_node_map/', views.index_node_map, name='index_node_map'),
    path('search/', views.search, name='search'),
    path('node_map/', views.node_map, name='node_map'),
    path('results_report/', views.results_report, name='results_report'),
    path('contact/', views.contact, name='contact'),
    path('acknowledgements/', views.acknowledgements, name='acknowledgements'),
    path('about/', views.about, name='about')
]

cohabio/mapper/models.py
from django.db import models


class User(models.Model):
    workplace = models.CharField(max_length=200)
    transport = models.CharField(max_length=200)
    max_commute = models.IntegerField()
    elements = models.IntegerField()


class SearchResults(models.Model):
    time_stamp = models.DateTimeField(auto_now_add=True)
    you = models.ForeignKey(User, null=False, on_delete=models.CASCADE, related_name='results_you')
    them = models.ForeignKey(User, null=False, on_delete=models.CASCADE, related_name='results_them')
    results = models.IntegerField(default=0)

    class Meta:
        ordering = ['time_stamp']


class PlaceData(models.Model):
    name = models.CharField(max_length=200)
    latitude = models.DecimalField(max_digits=20, decimal_places=8)
    longitude = models.DecimalField(max_digits=20, decimal_places=8)
    population = models.IntegerField(null=True)
    usage = models.FloatField(null=True)
    country_code = models.CharField(max_length=5)
    source = models.CharField(max_length=10)

    def __str__(self):
        return self.name

cohabio/mapper/forms.py
from django import forms


class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['contact_name'].label = "Your name:"
        self.fields['contact_email'].label = "Your email:"
        self.fields['content'].label = "Your message:"

cohabio/mapper/views.py
from collections import defaultdict, OrderedDict
import logging

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import get_template
from django.core.mail import EmailMessage
from django.contrib import messages
from reportlab.pdfgen import canvas

from cohabio.config import GOOGLE_KEY, MAX_ENTRIES
from mapper.forms import ContactForm
from mapper.utils.dt import daily_elements
from mapper.utils.search import DynamicIntersection, EmptyIntersection
from mapper.utils.geo import GeoLocator
from mapper.utils.search import compare_users
from mapper.utils.pins import html_check
from mapper.utils.sets import UserSet

logger = logging.getLogger(__name__)


def index(request):
    context = {
        'loc1': str(request.session.get('sesh_work1', '')),
        'loc2': str(request.session.get('sesh_work2', '')),
        'tra1': request.session.get('sesh_tran1', ''),
        'tra2': request.session.get('sesh_tran2', ''),
        'tim1': str(request.session.get('sesh_mcom1', 45)),
        'tim2': str(request.session.get('sesh_mcom2', 45)),
        'che1': request.session.get('sesh_chec1', ['', '', '', '']),
        'che2': request.session.get('sesh_chec1', ['', '', '', '']),
        'api_key': GOOGLE_KEY,
    }
    return render(request, 'mapper/index_bootstrap.html', context)


def index_node_map(request):
    context = {
        'loc1': str(request.session.get('sesh_work1', '')),
        'loc2': str(request.session.get('sesh_work2', '')),
        'tra1': request.session.get('sesh_tran1', ''),
        'tra2': request.session.get('sesh_tran2', ''),
        'tim1': str(request.session.get('sesh_mcom1', 45)),
        'tim2': str(request.session.get('sesh_mcom2', 45)),
        'che1': request.session.get('sesh_chec1', ['', '', '', '']),
        'che2': request.session.get('sesh_chec1', ['', '', '', '']),
        'api_key': GOOGLE_KEY,
    }
    return render(request, 'mapper/index_node_map.html', context)


def node_map(request):
    if request.method == 'POST':
        geolocator = GeoLocator(logger=logger)

        search_id1 = request.POST.get('textfield1', None)
        search_id2 = request.POST.get('textfield2', None)
        transport_id1 = request.POST.getlist('transport1', None)
        transport_id2 = request.POST.getlist('transport2', None)
        max_commute_id1 = request.POST.get('maxcommute1', None)
        max_commute_id2 = request.POST.get('maxcommute2', None)
        request.session['sesh_work1'] = search_id1
        request.session['sesh_work2'] = search_id2
        request.session['sesh_tran1'] = html_check(transport_id1)[0]
        request.session['sesh_tran2'] = html_check(transport_id2)[0]
        request.session['sesh_mcom1'] = max_commute_id1
        request.session['sesh_mcom2'] = max_commute_id2
        request.session['sesh_chec1'] = html_check(transport_id1)[1]
        request.session['sesh_chec2'] = html_check(transport_id2)[1]

        origin1, origin2 = geolocator.return_gps_from_place_names([search_id1, search_id2])

        user1 = UserSet(workplace=origin1, modes=transport_id1, max_time=max_commute_id1)
        user2 = UserSet(workplace=origin2, modes=transport_id2, max_time=max_commute_id2)
        li = DynamicIntersection()
        probes1 = user1.get_nodes_within_boundary(li.scale)
        probes2 = user2.get_nodes_within_boundary(li.scale)

        reduced_intersect = li.adjust_intersect(user1, user2)

        mean_gps = geolocator.average_gps(search_id1, search_id2)
        work_coords = geolocator.return_gps_from_place_names([search_id1, search_id2])
        work_names = [search_id1, search_id2]
        who = ["you", "they"]
        col = ["#428bca", "#d9534f"]
        work_places = list(zip([[wc.latitude, wc.longitude] for wc in work_coords], work_names, who, col))
        coords = [([float(place.latitude), float(place.longitude)], col[0]) for place in probes1]
        coords.extend(([float(place.latitude), float(place.longitude)], col[1]) for place in probes2)
        coords.extend(([float(place.latitude), float(place.longitude)], '#5cb85c') for place in reduced_intersect)

        boxes = [(user1.boundary, col[0]), (user2.boundary, col[1])]

        context = {
            'mean_gps': mean_gps,
            'places': coords,
            'work_places': work_places,
            'boxes': boxes
        }
        return render(request, 'mapper/map_all_probes.html', context)


def search(request):
    if request.method == 'POST':
        quota_today = daily_elements()
        logger.info('Total elements before: %i' % quota_today)
        if quota_today > MAX_ENTRIES:
            return render(request, 'mapper/splashscreen.html')
        search_id1 = request.POST.get('textfield1', None)
        search_id2 = request.POST.get('textfield2', None)
        transport_id1 = request.POST.getlist('transport1', None)
        transport_id2 = request.POST.getlist('transport2', None)
        max_commute_id1 = request.POST.get('maxcommute1', None)
        max_commute_id2 = request.POST.get('maxcommute2', None)
        request.session['sesh_work1'] = search_id1
        request.session['sesh_work2'] = search_id2
        request.session['sesh_tran1'] = html_check(transport_id1)[0]
        request.session['sesh_tran2'] = html_check(transport_id2)[0]
        request.session['sesh_mcom1'] = max_commute_id1
        request.session['sesh_mcom2'] = max_commute_id2
        request.session['sesh_chec1'] = html_check(transport_id1)[1]
        request.session['sesh_chec2'] = html_check(transport_id2)[1]
        error_message = ''
        if search_id1 == '' or search_id2 == '':
            error_message = 'Please tell us where you work!'
        elif transport_id1 == [] or transport_id2 == []:
            error_message = 'Please ensure transport options are selected!'
        elif search_id1 == search_id2:
            error_message = 'If you both work in the same place, why not live there!'
        if error_message:
            messages.add_message(request, messages.INFO, error_message)
            return HttpResponseRedirect('/')

        geolocator = GeoLocator(logger=logger)
        user1 = UserSet(
            workplace=search_id1,
            modes=transport_id1,
            max_time=max_commute_id1,
            geolocator=geolocator,
            name="you"
        )
        user2 = UserSet(
            workplace=search_id2,
            modes=transport_id2,
            max_time=max_commute_id2,
            geolocator=geolocator,
            name="them"
        )

        try:
            output = compare_users(user1, user2)
            quota_today = daily_elements()
            logger.info('Total elements after: {}'.format(quota_today))
        except EmptyIntersection as e:
            logger.error(e)
            messages.add_message(request, messages.INFO,
                                 'No results! Try increasing commute times, or choosing a different transport method.')
            return HttpResponseRedirect('/')
        except Exception as e:
            logger.error(e)
            messages.add_message(request, messages.INFO, "We're not sure what happened...")
            return HttpResponseRedirect('/')
        else:
            mean_gps = geolocator.average_gps(search_id1, search_id2)
            work_coords = geolocator.return_gps_from_place_names([search_id1, search_id2])
            work_names = [search_id1, search_id2]
            who = ["you", "they"]
            col = ["#428bca", "#d9534f"]
            work_places = list(zip([[wc.latitude, wc.longitude] for wc in work_coords], work_names, who, col))

            coords = [[float(place.latitude), float(place.longitude)] for place in output]
            html = [pl['html'] for pl in output.values()]
            context = {
                'mean_gps': mean_gps,
                'places': list(zip(coords, html)),
                'work_places': work_places,
            }
            request.session.update(context)
            request.session['user1modes'] = [modes.get('user1') for modes in output.values()]
            request.session['user2modes'] = [modes.get('user2') for modes in output.values()]
            request.session['locations'] = [str(loc) for loc in output.keys()]
            return render(request, 'mapper/map7.html', context)
    else:
        context = {
            'mean_gps': request.session['mean_gps'],
            'places': request.session['places'],
            'work_places': request.session['work_places'],
        }
        return render(request, 'mapper/map7.html', context)


def results_report(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="cohabio_report.pdf"'
    # Create the PDF object, using the response object as its "file."
    p = canvas.Canvas(response)
    # Draw things on the PDF. Here's where the PDF generation happens.
    # See the ReportLab documentation for the full list of functionality.
    p.setFont('Courier-Bold', 16)
    p.drawString(242, 800, "Cohabio Report")
    p.setFont('Courier-Bold', 9)
    p.drawString(30, 775, "Location")
    location1 = "Distance to " + str((request.session['sesh_work1'].split(","))[0])
    location2 = "Distance to " + str((request.session['sesh_work2'].split(","))[0])
    p.drawString(155, 775, location1)
    p.drawString(380, 775, location2)
    p.setFont('Courier', 9)
    position = 750
    locations = request.session['locations']
    user1modes = request.session['user1modes']
    user2modes = request.session['user2modes']

    def format_duration_line(user_modes):
        out_list = []
        for mode in user_modes:
            out_list.append(str(mode[0][0]) + ', ' + str(int(mode[0][1])) + ' mins')
        return out_list

    user1modetimes = format_duration_line(user1modes)
    user2modetimes = format_duration_line(user2modes)
    for idx, item in enumerate(locations):

cohabio/mapper/templates/mapper/about_us.html
{% extends 'mapper/base.html' %}
{% block title %}About - {{ block.super }}{% endblock %}

{% block content %}

<h1 class="sub-heading" style="font-size: 40px;">About</h1>

<hr>

<maintext>
    <div style="text-align: justify; text-justify: inter-word;">
        In an ideal world, we would all live a comfortable distance from our places of work; for the sake of
        healthier, happier, and more efficient societies. Unfortunately, this is often not possible. Whether the cause is
        economic pressure or misfortune, cohabio can help us find a place to live that maximises the time we have
        with friends and loved ones, at the expense of a hefty commute.
        <br>
        <br>
        Our algorithms compare thousands of potential home locations based on the minimum expected commuting time for both
        you and your partner. They take into account your preferred method(s) of transportation, and whether you have a
        hard limit on the length of time you are willing to travel. Cohabio is the only site that provides this service for
        any location on planet Earth!
    </div>
</maintext>

<br>

<!--<a type="button" class="btn btn-default" style="font-size: 25px;" href="{% url 'mapper:index' %}">Home</a>-->
<form role="form" method="post" style="display:inline;" action="{% url 'mapper:index' %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-default" style="font-size: 25px;" value="back" name="back">Home</button>
</form>



{% endblock %}

cohabio/mapper/templates/mapper/acknowledgements.html
{% extends 'mapper/base.html' %}
{% block title %}Acknowledgements - {{ block.super }}{% endblock %}

{% block content %}

<h1 class="sub-heading" style="font-size: 40px;">Acknowledgements</h1>

<hr>

<maintext>
    <ul>
        <li><a href="http://www.geonames.org/" target="_blank">GeoNames</a>
            - Provided database of global cities from which suggestions are made.</li>
        <li><a href="https://developers.google.com/maps/documentation/" target="_blank">Google</a>
            - Google Maps Distance Matrix and Google Maps Time Zone APIs</li>
        <li><a href="http://orr.gov.uk/statistics/published-stats/station-usage-estimates" target="_blank">ORR</a>
            - Estimates of UK train station usage.</li>
        <li><a href="https://data.london.gov.uk/dataset/london-underground-performance-reports/" target="_blank">TfL</a>
            - Estimates of London tube station usage.</li>
        <li><a href="https://tfl.gov.uk/info-for/open-data-users/" target="_blank">TfL</a>
            - Database of all public transport stations in the Greater London Area.</li>
        <li><a href="https://developer.wmata.com/docs/services/" target="_blank">WMATA</a>
            - API for all Washington DC metro stations.</li>
    </ul>
</maintext>

<br>

<!--<a type="button" class="btn btn-default" style="font-size: 25px;" href="{% url 'mapper:index' %}">Home</a>-->
<form role="form" method="post" style="display:inline;" action="{% url 'mapper:index' %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-default" style="font-size: 25px;" value="back" name="back">Home</button>
</form>


{% endblock %}

cohabio/mapper/templates/mapper/base.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
    <title>
         {% block title %}cohabio{% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'mapper/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'mapper/title.css' %}" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Dosis:400|Oleo+Script" rel="stylesheet" />

    <style>
    body {
        margin: auto;
        top: 50px;
        height: 80%;
        width: 70%;
        background: #A3D7E1;
        font-family: 'Dosis', sans-serif;
        font-size: 20px;
    }

    maintext {
        font-family: 'Dosis', sans-serif;
        font-size: 30px;
    }
    </style>
    <script>
    function goBack() {
        window.history.back()
    }
    </script>
    {% block header %}{% endblock %}
</head>
<body>
    <header>
        <h1>
            <span class="title_first">cohab</span><span class="title_last">io</span>
        </h1>
    </header>
    {% block content %}{% endblock %}
    {% block footer %}{% endblock %}

    <hr>
</body>
</html>

cohabio/mapper/templates/mapper/contact.html
{% extends 'mapper/base.html' %}
{% block title %}Contact - {{ block.super }}{% endblock %}

{% block content %}
<h1 class="sub-heading" style="font-size: 40px;">Contact - We appreciate your feedback!</h1>

<hr>



<form role="form" method="post" style="display:inline;" id="myForm" action="{% if from %}?next={{ from }}{% endif %}">
    {% csrf_token %}
    {{ form.as_p }}
    <br>
    <input type="hidden" name="next" value="{{ request.path }}">
    <button class="btn btn-success " style="font-size: 25px;" type="submit" value="submit" name="submit">Submit</button>
</form>

<form role="form" method="post" style="display:inline;" action="{% if from %}?next={{ from }}{% endif %}">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.path }}">
    <button type="submit" class="btn btn-default" style="font-size: 25px;" name="back">Back</button>
</form>

<form role="form" method="post" style="display:inline;" action="{% url 'mapper:index' %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-default" style="font-size: 25px;" value="back" name="back">Home</button>
</form>


<script>
$(document).ready(function() {
    $("#backButton").click(function(event) {
        if( !confirm('Are you sure that you want to submit the form') ){
            event.preventDefault();
        }

    });
});
</script>


{% endblock %}

cohabio/mapper/templates/mapper/index_bootstrap.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>cohabio | Find a place to commute from together</title>
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<meta name="description" content="cohabio is a free global service providing suggested home location for cohabitants that commute to different work places.">
		<script src="{% static 'mapper/spin.min.js' %}"></script>
        <script src="{% static 'mapper/ladda.min.js' %}"></script>
		<link rel="stylesheet" href="{% static 'mapper/ladda-themeless.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'mapper/bootstrap.css' %}" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
        <link href="{% static 'mapper/bootstrap-slider.css' %}" rel="stylesheet" />
        <script src="{% static 'mapper/bootstrap-slider.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'mapper/title.css' %}" />
        <link href="https://fonts.googleapis.com/css?family=Dosis:400|Oleo+Script" rel="stylesheet" />
        <link rel='shortcut icon' type="image/png" href="{% static 'mapper/favicon.ico' %}" />
	    <script>
        $(document).ready( function() {
            $("#sl1").slider({
                tooltip: 'hide',
	            selection: 'before'
            });
            $("#sl1").on("slide", function(slideEvt) {
	            $("#sl1SliderVal").text(slideEvt.value);
            });
            $("#sl2").slider({
                tooltip: 'hide',
                selection: 'before'
            });
            $("#sl2").on("slide", function(slideEvt) {
	            $("#sl2SliderVal").text(slideEvt.value);
            });
        });
        </script>
        <script>
            Ladda.bind( '.button-demo .ladda-button', { timeout: 2000 } );
        </script>
        {% if api_key %}
            <script src="https://maps.googleapis.com/maps/api/js?key={{ api_key }}&libraries=places&language=en"></script>
        {% endif %}
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
            ga('create', 'UA-84104870-1', 'auto');
            ga('send', 'pageview');
        </script>
    </head>
    <body>
        <div class="jumbotron">
          <div class="container">
            <h1>
                <span class="title_first">cohab</span><span class="title_last">io</span>
            </h1>
            <h3 class="sub-heading">Moving to a new city? Want to live together, but work in different places? We can help.</h3>
          </div>
        </div>
        <form method="POST" action="{% url 'mapper:search' %}" id="localStorageTest">
            {% csrf_token %}
            <div class="container">
                {% if error_message %}<h4 style="color:red; font-family: 'Dosis', sans-serif;"><strong>{{ error_message }}</strong></h4>{% endif %}
                {% if messages %}
                    {% for message in messages %}
                        <h4 style="color:red; font-family: 'Dosis', sans-serif;" class="messages"><strong>{{ message }}</strong></h4>
                    {% endfor %}
                {% endif %}
                <div class="row">
                    <div class="col-md-6">
                        <br>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1">Where you work:</span>
                            <input type="text" class="form-control" placeholder="Your workplace" aria-describedby="basic-addon1" name="textfield1" id="autocomplete1" value="{{loc1}}">
                            <script>
                              var input = document.getElementById('autocomplete1');
                              new google.maps.places.Autocomplete(input);
                            </script>
                        </div>
                        <br>
                        <div class="container-fluid">
                            <span>How long do you want to travel?&nbsp;&nbsp;</span>
                            <input type="text" name="maxcommute1" value="{{tim1}}" id="sl1" data-slider-id='time_slider' data-slider-min="0" data-slider-max="90" data-slider-step="5" data-slider-value="{{tim1}}" />
                            <span id="sl1CurrentSliderValLabel">&nbsp;&nbsp;<b><span id="sl1SliderVal">{{tim1}}</span> mins</b></span>
                        </div>
                        <br>
                        <div class="container-fluid">
                            <span>Your preferred mode of transport:&nbsp;&nbsp;</span>
                            <div class="btn-group" data-toggle="buttons">
                                <label class="btn btn-primary {{tra1.0}}">
                                    <input type="checkbox" autocomplete="off" name="transport1" value="walking" {{che1.0}}>Walk
                                </label>
                                <label class="btn btn-primary {{tra1.1}}">
                                    <input type="checkbox" autocomplete="off" name="transport1" value="bicycling" {{che1.1}}>Bike
                                </label>
                                <label class="btn btn-primary {{tra1.2}}">
                                    <input type="checkbox" autocomplete="off" name="transport1" value="driving" {{che1.2}}>Car
                                </label>
                                <label class="btn btn-primary {{tra1.3}}">
                                    <input type="checkbox" autocomplete="off" name="transport1" value="transit" {{che1.3}}>Public Transport
                                </label>
                            </div>
                        </div>
                        <br>
                    </div>
                    <div class="col-md-6">
                        <br>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon2">Where they work:</span>
                            <input type="text" class="form-control" placeholder="Their workplace" aria-describedby="basic-addon2" name="textfield2" id="autocomplete2" value="{{loc2}}">
                            <script>
                              var input = document.getElementById('autocomplete2');
                              new google.maps.places.Autocomplete(input);
                            </script>
                        </div>
                        <br>
                        <div class="container-fluid">
                            <span>How long do they want to travel?&nbsp;&nbsp;</span>
                            <input type="text" name="maxcommute2" value="{{tim2}}" id="sl2" data-slider-id='time_slider2' data-slider-min="0" data-slider-max="90" data-slider-step="5" data-slider-value="{{tim2}}"/>
                            <span id="sl2CurrentSliderValLabel">&nbsp;&nbsp;<b><span id="sl2SliderVal">{{tim2}}</span> mins</b></span>
                        </div>
                        <br>
                        <div class="container-fluid">
                            <span>Their preferred mode of transport:&nbsp;&nbsp;</span>
                            <div class="btn-group" data-toggle="buttons">
                                <label class="btn btn-danger {{tra2.0}}">
                                    <input type="checkbox" autocomplete="off" name="transport2" value="walking" {{che2.0}}>Walk
                                </label>
                                <label class="btn btn-danger {{tra2.1}}">
                                    <input type="checkbox" autocomplete="off" name="transport2" value="bicycling" {{che2.1}}>Bike
                                </label>
                                <label class="btn btn-danger {{tra2.2}}">
                                    <input type="checkbox" autocomplete="off" name="transport2" value="driving" {{che2.2}}>Car
                                </label>
                                <label class="btn btn-danger {{tra2.3}}">
                                    <input type="checkbox" autocomplete="off" name="transport2" value="transit" {{che2.3}}>Public Transport
                                </label>
                            </div>
                        </div>
                        <br>
                    </div>
                </div>
                <br>
                <br>
                <section>
                    <button class="btn btn-success btn-lg ladda-button" data-color="green" data-style="expand-left" type="submit"><span class="ladda-label">Search</span></button>            <!--<button id="about-btn"> Click Me - I'm Javascript on Speed</button>-->
                </section>
                <hr>
            </div>
        </form>
        <script>
			// Bind normal buttons
			Ladda.bind( 'section:not(.progress-demo) button', { timeout: 1000000 } );
		</script>
        <style>
            #navigation
            {
                font-size: 20px;
                font-family: 'Dosis', sans-serif;
            }
            #navigation ul
            {
                margin: 0;
                padding: 0;
            }
            #navigation ul li
            {
                list-style-type: none;
                display: inline;
            }
            #navigation li:not(:first-child):before {
                content: " | ";
            }
        </style>
        <footer class="container">
            <div class="row">
                <div id="navigation">
                    <div align="left" class="col-md-6">
                        <ul>
                            <li><a href="{% url 'mapper:contact' %}?from={{ request.path|urlencode }}">Contact</a></li>
                            <li><a href="{% url 'mapper:about' %}">About</a></li>
                            <li><a href="{% url 'mapper:acknowledgements' %}">Acknowledgements</a></li>
{#                            <li><a href="{% url 'mapper:support' %}">Support Us</a></li>#}
                        </ul>
                    </div>
                    <div align="right" class="col-md-6">
                        <span>A Will Haese-Hill and David C. Gershlick project</span>
                    </div>
                </div>
            </div>
        </footer>
    </body>
</html>